export const SET_REGION = "SET_REGION";
export const SET_USER_LOCATION = "SET_USER_LOCATION";

export const GET_STORIES_START = "GET_STORIES_START";
export const GET_STORIES_ERROR = "GET_STORIES_ERROR";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const FILTER_CHANGED = "FILTED_CHANGED";
