export const SET_REGION = "SET_REGION";
export const SET_USER_LOCATION = "SET_USER_LOCATION";

export const GET_USER_START = "GET_USER_START";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_STORIES_START = "GET_STORIES_START";
export const GET_STORIES_ERROR = "GET_STORIES_ERROR";
export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";

export const FILTER_CHANGED = "FILTED_CHANGED";
