export const SET_REGION = "SET_REGION";
export const SET_USER_LOCATION = "SET_USER_LOCATION";

export const GET_ANNOTATIONS_START = "GET_ANNOTATIONS_START";
export const GET_ANNOTATIONS_ERROR = "GET_ANNOTATIONS_ERROR";
export const GET_ANNOTATIONS_SUCCESS = "GET_ANNOTATIONS_SUCCESS";

export const FILTER_CHANGED = "FILTED_CHANGED";
